// This file is auto-generated by @hey-api/openapi-ts

export { DocumentIdService, type Options } from './sdk.gen';
export type { ClientOptions, DocumentIdModel, GetDocumentIdData, GetDocumentIdErrors, GetDocumentIdResponse, GetDocumentIdResponses } from './types.gen';
