// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetDocumentIdData, GetDocumentIdErrors, GetDocumentIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class DocumentIdService {
    public static getDocumentId<ThrowOnError extends boolean = false>(options: Options<GetDocumentIdData, ThrowOnError>): RequestResult<GetDocumentIdResponses, GetDocumentIdErrors, ThrowOnError> {
        return (options.client ?? client).get<GetDocumentIdResponses, GetDocumentIdErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/dynamicdave-quicktools/api/v1/document/{key}/id',
            ...options
        });
    }
}
