// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44413' | (string & {});
};

export type DocumentIdModel = {
    id: number;
};

export type GetDocumentIdData = {
    body?: never;
    path: {
        key: string;
    };
    query?: never;
    url: '/umbraco/dynamicdave-quicktools/api/v1/document/{key}/id';
};

export type GetDocumentIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetDocumentIdResponses = {
    /**
     * OK
     */
    200: DocumentIdModel;
};

export type GetDocumentIdResponse = GetDocumentIdResponses[keyof GetDocumentIdResponses];
